#!/usr/bin/env bash
#This script is displaying "Best School" 10 times

i=0
while true
do
	((i++))
if ((i==4))
then
	echo "bad luck"
elif((i==8))
then
	echo "good luck"
else
	echo "Best School"
fi
if ((i > 9))
then
	break
fi
done
